### ISSUE TITLE
Change N to Nsamp_adj to work with current r4ss?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pacific-hake/pacifichakemse#10]
To work with recent versions of SS and r4ss, I had to change the `N` in this line to `Nsamp_adj`:
https://github.com/pacific-hake/pacifichakemse/blob/4ad9f370690addd1ddd6c9be29d1ed20a11f880a/R/ss_model_loading.R#L523

The column name in Stock Synthesis output changed a while ago, and then more recently r4ss was changed to not allow partial matching as discussed at length here https://github.com/r4ss/r4ss/issues/442. Given that we're all using the executable included in this package, I'm assuming it's the r4ss change that tripped me up. @cgrandin or @kristinmarshall-NOAA, maybe you can make this simple change and confirm that the code still works for you.

**Comment by kristinmarshall-NOAA** [comment]
I had to change N to NSamp_adj to get it to run, too.  I meant to post an issue about it a couple of weeks ago but hadn't. It looks like this change was made recently in 6296c5e97c632ea5ed0783205a21390bce99f433

**Comment by cgrandin** [comment]
I’ve been changing it back and forth a few times. I’m not sure why but it suddenly doesn’t work and I change it back again. So I will have to figure out why on my end.

**Comment by cgrandin** [comment]
This was because I was using an old branch of r4ss during the beginning of the hale assessment set up, before we merged it.

**Comment by kristinmarshall-NOAA** [comment]
This still seems to be an issue.  I just had to change it back to ss=N to get it to run on my new machine I'm setting up.
