### ISSUE TITLE
errors generated from run_om(), more specifically load_dat_om()

### ISSUE THREAD

**Issue by kristinmarshall-NOAA** [pacific-hake/pacifichakemse#12]
I'm getting an error from load_dat_OM.R.  For example - if I try to run the run_om_attainment_unfished.R file, I get an error from the [run_OM() function](https://github.com/pacific-hake/runhakemse/blob/c28c8042b42341b9bde875eb9d0d9855a6c0934f/R/run_om_attainment_unfished.R#L24): 

 Error: Can't combine `..1$Yr` <integer> and `..2$Yr` <character>.
The traceback takes me to: 	
df %>% bind_rows(new_df) at load_dat_om.R#277

Does this ring any bells for you @cgrandin? I was initially thinking it was coming from something in the recent (Nov) commits. I backed up several commits to test that but still got the error.  So then, I backed up both reposall the way to the May 17 commits, and generates different earlier errors.  There could definitely be some operator error on my end or something with my particular configuration.

@aaronmberger-nwfsc had you succesfully run the run_om() or run_mse() functions in the fall on your machine?

**Comment by cgrandin** [comment]
I'd have to see your script to figure out what's going on. I haven't seen that error before..

I did receive your email about bookdown but we are essentially at max capacity trying to get the assessment done so I haven't had a minute to think about it :(

**Comment by kristinmarshall-NOAA** [comment]
Closing this.  Resolved with installing R4ss from github (not CRAN).  Also, resolved potential package incompatibility issues by installing an earlier version of the Matrix package to be compatible with TMB, and reinstalling Rcpp.  Thanks to @cgrandin  for debugging help.
